name: Build OpenML Python

on:
  push:
    branches:
      - master
      - 'hf-*'    # hotfix branches
    tags:
      - '*.*.*'   # release tag xx.yy.zz
  pull_request:
    branches:
      - master
      - 'hf-*'

jobs:

  # Build and test job
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch -f --tags
          echo exit code $?
          git tag --list

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Start Docker
        run: |
          docker pull feedzai/oracle-jep-miniconda:1.0.2 &&
            docker run -v $(pwd):/opt/openml -d --name test-container feedzai/oracle-jep-miniconda:1.0.2 top -b

      - name: Install in Docker
        run: docker exec test-container bash -v /opt/openml/scripts/maven-with-jep.sh install -f /opt/openml/pom.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Test in Docker
        run: docker exec test-container bash -v /opt/openml/scripts/maven-with-jep.sh -f /opt/openml/pom.xml test

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
